# $FreeBSD: head/usr.sbin/bsdinstall/scripts/Makefile 256343 2013-10-11 20:41:35Z dteske $

SCRIPTS= auto adduser checksum config docsinstall entropy hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= /usr/libexec/bsdinstall

NO_MAN=	true

.include <bsd.prog.mk>
