# $FreeBSD: head/sys/boot/i386/zfsloader/Makefile 212066 2010-08-31 19:01:12Z delphij $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" x86
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
MAN=

.include "${.CURDIR}/../loader/Makefile"

