# $FreeBSD: head/tests/sys/Makefile 261615 2014-02-08 00:20:21Z asomers $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/..

TESTS_SUBDIRS+=		kern
TESTS_SUBDIRS+=		netinet
TESTSDIR= ${TESTSBASE}/sys

KYUAFILE= yes

.include <bsd.test.mk>
