# $FreeBSD:  263738 2014-03-25 15:03:08Z asomers $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH+=	fibs_test
PROG=	udp_dontroute
SRCS=	udp_dontroute.c
NO_MAN=
WARNS?=	6

.include <bsd.test.mk>
