# $FreeBSD: head/tools/tools/npe/npestats/Makefile 262832 2014-03-06 07:50:54Z adrian $

PROG=	npestats
SRCS=	main.c npestats.c
BINDIR=	/usr/local/bin
MAN=
USEPRIVATELIB=
LDADD=	-lbsdstat

.include <bsd.prog.mk>
