# $FreeBSD: head/usr.bin/join/Makefile 263227 2014-03-16 08:04:06Z jmmv $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=	join

.if ${MK_TESTS} != "no"
SUBDIR+= tests
.endif

.include <bsd.prog.mk>
