# $FreeBSD: head/usr.sbin/etcupdate/Makefile 263226 2014-03-16 04:09:22Z jmmv $

.include <bsd.own.mk>

SCRIPTS=etcupdate.sh
MAN=	etcupdate.8

.if ${MK_TESTS} != "no"
SUBDIR+= tests
.endif

.include <bsd.prog.mk>
