# $FreeBSD: head/tools/tools/wtap/vis_map/Makefile 232940 2012-03-13 20:30:23Z adrian $

BINDIR?=	/usr/local/bin/
PROG=	vis_map
SRC=	vis_map.c
MAN=

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
